# Generated by Django 3.2.6 on 2021-12-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='updated',
        ),
    ]
